### ISSUE TITLE
Bring a "how to get your data in" slide before the ladder plot

### ISSUE THREAD

**Issue by mienkoja** [mienkoja/SSWR_R_Workshop_2015#6]

**Comment by smithrichardj** [comment]
I guess the ladder plot isn't in the presentation yet. I added a slide on "how to get your data in" by expanding slide 8 with the read.csv command. I played with the size of some of the graphs nearby. This can be moved around as needed.

**Comment by mienkoja** [comment]
Reopening this issue as this didn't make it into the master repo

**Comment by smithrichardj** [comment]
I think I accidentally made two pull requests--delete one if you can.
